---
extends: default

rules:
  comments:
    level: error
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start:
    level: error
  line-length:
    max: 120
  truthy:
    level: error
