---
namespace: davidbarton
name: mac
version: 1.0.1
readme: README.md

authors:
  - davidbarton

description: Ansible collection for macOS setup automation

license:
  - MIT

tags:
  - mac
  - macos
  - osx
  - homebrew
  - brew
  - dock
  - dockutil
  - tools

dependencies:
  community.general: ">=6.0.0"

repository: https://github.com/davidbarton/ansible-collection-mac

build_ignore:
  - .github
  - tests
