---
- name: Install software with Homebrew.
  tags: [homebrew]
  block:
    - name: Check if brew package is installed.
      ansible.builtin.command: "brew --version"
      register: brew_check_output
      changed_when: false

    - name: Update Homebrew.
      ansible.builtin.command: "brew update --force"
      register: brew_update_output
      changed_when: brew_update_output.rc != 0
      when: homebrew_update

    - name: Add Homebrew taps.
      community.general.homebrew_tap:
        tap: "{{ item._name | default(item) }}"
        state: "{{ item._state | default('present') }}"
        url: "{{ item._url | default(omit) }}"
      loop: "{{ homebrew_taps }}"

    - name: Add Homebrew packages.
      community.general.homebrew:
        name: "{{ item._name | default(item) }}"
        state: "{{ item._state | default('present') }}"
        install_options: "{{ item._install_options | default(omit) }}"
      loop: "{{ homebrew_packages }}"

    - name: Upgrade Homebrew packages.
      community.general.homebrew:
        upgrade_all: true
      when: homebrew_upgrade_packages

    - name: Add Homebrew cask applications.
      community.general.homebrew_cask:
        name: "{{ item._name | default(item) }}"
        state: "{{ item._state | default('present') }}"
        install_options: "{{ item._install_options | default(omit) }}"
        accept_external_apps: "{{ _homebrew_cask_accept_external_apps | default(false) }}"
        sudo_password: "{{ ansible_become_password | default(omit) }}"
        greedy: "{{ _homebrew_cask_greedy | default(false) }}"
      loop: "{{ homebrew_cask_applications }}"

    - name: Upgrade Homebrew cask applications.
      community.general.homebrew_cask:
        upgrade_all: true
      when: homebrew_cask_upgrade_applications
  rescue:
    - name: The brew package operation error.
      ansible.builtin.fail:
        msg: >
          "{{ 'The brew package is not installed. Please install it.'
          if brew_check_output.rc != 0
          else 'The brew package operation error.' }}"
