---
# Homebrew taps to add.
homebrew_taps: []
# homebrew_taps:
#   - homebrew/core
#   - homebrew/cask

# Homebrew packages to add.
homebrew_packages: []
# homebrew_packages:
#   - bash
#   - zsh

# Homebrew cask applications to add.
homebrew_cask_applications: []
# homebrew_cask_applications:
#   - iterm2
#   - firefox

# Update Homebrew if true.
homebrew_update: true

# Upgrade Homebrew packages if true.
homebrew_upgrade_packages: false

# Upgrade Homebrew cask if true.
homebrew_cask_upgrade_applications: false
