---
name: CI

on:
  push:
    # Trigger on push to main branch
    branches:
      - main
    # Trigger on every tag push
    tags:
      - "*"

  # Trigger on every pull request
  pull_request:

  # Trigger every Sunday midnight
  schedule:
    - cron: "0 0 * * 0"

  # Trigger manually here https://github.com/davidbarton/ansible-collection-mac/actions/workflows/ci.yml
  # The manual trigger is used to record new test expectations
  workflow_dispatch:
    inputs:
      record_test:
        description: "Record new test expectations."
        required: true
        default: true
        type: boolean

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v3

      - name: Run ansible-lint.
        uses: ansible/ansible-lint-action@v6

  test:
    name: Test
    runs-on: macos-latest
    env:
      ANSIBLE_COLLECTIONS_PATHS: ../../../
      ANSIBLE_FORCE_COLOR: true
      ANSIBLE_ANY_ERRORS_FATAL: true
      ANSIBLE_CONFIG: tests/ansible.cfg
    defaults:
      run:
        working-directory: ansible_collections/davidbarton/mac
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v3
        with:
          path: ansible_collections/davidbarton/mac

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Install Python dependencies.
        run: pip install -r tests/requirements.txt

      - name: Install Ansible Galaxy dependencies.
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            cd ansible_collections/davidbarton/mac
            ansible-galaxy install -r tests/requirements.yml

      - name: Install dockutil package using Homebrew.
        run: |
          # Use cask temporarily for dockutil
          # https://github.com/kcrawford/dockutil/issues/127#issuecomment-1118733013
          brew install hpedrorodrigues/tools/dockutil

      - name: Download test.log.
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test.log
          path: ansible_collections/davidbarton/mac/expected.test.log
          workflow_conclusion: success
          if_no_artifact_found: warn

      - name: Download idempotence.log.
        uses: dawidd6/action-download-artifact@v2
        with:
          name: idempotence.log
          path: ansible_collections/davidbarton/mac/expected.idempotence.log
          workflow_conclusion: success
          if_no_artifact_found: warn

      - name: Run test.
        run: >
          ansible-playbook tests/test.yml --tags all
          | tee test.log

      - name: Run idempotence test.
        run: >
          ansible-playbook tests/test.yml --tags all
          | tee idempotence.log

      - name: Assert test.log.
        uses: GuillaumeFalourd/diff-action@v1
        with:
          first_file_path: ansible_collections/davidbarton/mac/expected.test.log
          second_file_path: ansible_collections/davidbarton/mac/test.log
          expected_result: PASSED
        if: ${{ !inputs.record_test && hashFiles('ansible_collections/davidbarton/mac/expected.test.log') }}

      - name: Assert idempotence.log.
        uses: GuillaumeFalourd/diff-action@v1
        with:
          first_file_path: ansible_collections/davidbarton/mac/expected.idempotence.log
          second_file_path: ansible_collections/davidbarton/mac/idempotence.log
          expected_result: PASSED
        if: ${{ !inputs.record_test && hashFiles('ansible_collections/davidbarton/mac/expected.idempotence.log') }}

      - name: Upload test.log.
        uses: actions/upload-artifact@v3
        with:
          name: test.log
          path: ansible_collections/davidbarton/mac/test.log

      - name: Upload idempotence.log.
        uses: actions/upload-artifact@v3
        with:
          name: idempotence.log
          path: ansible_collections/davidbarton/mac/idempotence.log

  release:
    name: Release
    if: github.event.push.tags
    needs:
      - lint
      - test
    uses: ./.github/workflows/release.yml
    secrets: inherit
