---
name: Release

concurrency:
  group: release
  cancel-in-progress: true

on:
  workflow_call:

env:
  VERSION_NAME: ${{ github.ref_name }}
  BUILD_ARTIFACT_NAME: davidbarton-mac-${{ github.ref_name }}.tar.gz

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Install Python dependencies.
        run: pip install -r tests/requirements.txt

      - name: Pre-release check.
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        run: ansible-playbook tests/pre-release.yml

  build:
    name: Build
    needs:
      - pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Install Python dependencies.
        run: pip install -r tests/requirements.txt

      - name: Build Ansible collection.
        run: ansible-galaxy collection build

      - name: Upload build artifact.
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_NAME }}

  release:
    name: Release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v3

      - name: Download build artifact.
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}

      - name: Create Github release.
        run: gh release create ${{ env.VERSION_NAME }} ${{ env.BUILD_ARTIFACT_NAME }} --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Install Python dependencies.
        run: pip install -r tests/requirements.txt

      - name: Download build artifact.
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}

      - name: Publish Ansible collection.
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: ansible-galaxy collection publish ${{ env.BUILD_ARTIFACT_NAME }} --token ${{ env.ANSIBLE_GALAXY_TOKEN }}
